### ISSUE TITLE
Instructions and code to upload training data points to GEE

### ISSUE THREAD

**Issue by GMoncrieff** [Geethen/Invasive_Species_Mapping#2]
Add documentation in code cells and repo readme describing how to upload your data to GEE from the notebook. This will involve using a command-line tool for GEE uploading e.g. [geeup](https://github.com/samapriya/geeup) and a clear outline of the required schema and column encoding. We should add some test to confirm that the users data conforms to the expected schema before upload

**Comment by Geethen** [comment]
documentation updated and example with geeup provided
